Erp\Bundle\CoreBundle\Entity\FileItem:
  type: entity
  table: core_fileitem
  id:
    id:
      type: bigint
      generator:
        strategy: IDENTITY
  fields:
    data:
      type: blob
      nullable: false
    mimeType:
      type: string
      length: 64
      nullable: false
    roles:
      type: simple_array
      nullable: true
