Erp\Bundle\CoreBundle\Entity\TempFileItem:
  type: entity
  table: core_tempfileitem
  id:
    uuid:
      type: string
      length: 64
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Erp\Bundle\CoreBundle\Infrastructure\ORM\UuidGenerator
  fields:
    tstmp:
      type: datetime_immutable
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
    data:
      type: blob
      nullable: false
    mimeType:
      type: string
      length: 64
      nullable: false
