Erp\Bundle\CoreBundle\Entity\Thing:
  type: entity
  table: thing
  indexes:
    thing_active_idx:
      columns: [ active ]
  id:
    id:
      type: bigint
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
      nullable: false
    active:
      type: boolean
      nullable: false
      options:
        default: true
