Erp\Bundle\CoreBundle\Entity\Thing:
  type: entity
  table: thing
  id:
    id:
      type: bigint
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
      nullable: false
